# Numpy

numpy позволяет оперировать матрицами и векторами

## Установка

В нужном окружении запустить

```
conda install numpy
```

In [2]:
import numpy as np

In [2]:
test_list = [1, 2, 3]
array = np.array(test_list)
print(array, array.shape, len(array))

[1 2 3] (3,) 3


In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [19]:
matrix = [[1, 2, 3], [4, 5, 6]]
np_matrix = np.array(matrix)
print(np_matrix)
print(np_matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
np_matrix.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np_matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [15]:
np_matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Базовые операции

In [22]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [23]:
a + b

array([20, 29, 38, 47])

In [25]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [27]:
b < 2

array([ True,  True, False, False])

In [28]:
b[b < 2]

array([0, 1])

In [31]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

Поэлементное произведение

In [32]:
A * B

array([[2, 0],
       [0, 4]])

Произведение матриц

In [30]:
A @ B

array([[5, 4],
       [3, 4]])

In [33]:
A.dot(B) # тоже самое

array([[5, 4],
       [3, 4]])

## Задача - Решение СЛАУ

$$Ax = b$$

In [5]:
A = np.array([
    [3, -2],
    [5, 1]]
)
b = np.array([-6, 3])
# Решение - [0, 3]

In [ ]:
# Ваш код здесь


Решим методом Крамера

https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0

In [6]:
# Ваш код здесь

np.linalg.det(A) # Определитель матрицы A

13.0

Транспонирование

In [88]:
B

array([[2, 0],
       [3, 4]])

In [89]:
B.T

array([[2, 3],
       [0, 4]])

Создание случайного массива

In [93]:
rand_arr = np.random.normal(0, 1, size=(2, 5))
rand_arr

array([[-1.72614878, -1.7628622 ,  0.93080971, -0.68183606,  0.32603148],
       [ 0.19704034, -1.03571061,  1.15179705, -0.57753003, -0.01904176]])

In [94]:
rand_arr[rand_arr > 0]

array([0.93080971, 0.32603148, 0.19704034, 1.15179705])

In [95]:
rand_arr.sum(axis=0)

array([-1.52910844, -2.79857281,  2.08260676, -1.25936609,  0.30698971])

In [96]:
rand_arr.sum(axis=1)

array([-2.91400586, -0.28344501])

In [102]:
rand_arr.max(), rand_arr.min()

(1.1517970495328347, -1.76286220178673)

In [104]:
rand_arr.max(axis=0)

array([ 0.19704034, -1.03571061,  1.15179705, -0.57753003,  0.32603148])

In [105]:
np.sqrt(rand_arr)

C:\Users\koval\AppData\Local\Temp/ipykernel_4816/4099335953.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(rand_arr)


array([[       nan,        nan, 0.9647848 ,        nan, 0.57099166],
       [0.44389226,        nan, 1.07321808,        nan,        nan]])

## Задача

Вывести матрицу из нулей и единиц в шахматном порядке

In [ ]:
# Ваш код здесь


## Задача

Сгенерировать случайную матрицу и посчитать сумму положительных элементов в каждой строке, в каждом столбце.

In [ ]:
# Ваш код здесь


## Индексация

In [106]:
a = np.arange(10)

In [107]:
a[2]

2

In [108]:
a[2:5]

array([2, 3, 4])

In [109]:
a[:6:2]

array([0, 2, 4])

In [110]:
a[:6:2] = 1000
a

array([1000,    1, 1000,    3, 1000,    5,    6,    7,    8,    9])

In [111]:
a[::-1]

array([   9,    8,    7,    6,    5, 1000,    3, 1000,    1, 1000])

In [114]:
arr = np.random.randint(1, 5, size=(3, 5))
arr

array([[4, 3, 1, 3, 4],
       [1, 4, 1, 1, 3],
       [1, 2, 4, 3, 3]])

In [115]:
arr[2]

array([1, 2, 4, 3, 3])

In [116]:
arr[1:, :2]

array([[1, 4],
       [1, 2]])

In [118]:
arr[::-1, ::2] = 0
arr

array([[0, 3, 0, 3, 0],
       [0, 4, 0, 1, 0],
       [0, 2, 0, 3, 0]])

In [119]:
arr[-1]

array([0, 2, 0, 3, 0])

In [120]:
arr[:, :]

array([[0, 3, 0, 3, 0],
       [0, 4, 0, 1, 0],
       [0, 2, 0, 3, 0]])

## Расширяем массивы

In [128]:
a = np.arange(10)
b = a + 1

In [130]:
a.shape, b.shape

((10,), (10,))

In [133]:
np.hstack((a, b)).shape

(20,)

In [134]:
np.vstack((a, b)).shape

(2, 10)

In [135]:
np.hstack((a, [1]))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

Расширение массива в numpy происходит путем создания нового массива.

Поэтому если требуется сгенерировать массив, то лучше сделать это через список, а дальше сделать из него массив numpy

In [137]:
%%timeit

a = np.arange(10)
for i in range(1000):
    a = np.hstack((a, 1))
a.shape

6.57 ms ± 959 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [138]:
%%timeit

a = list(range(10))
for i in range(1000):
    a.append(i)
np.array(a).shape

152 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Сравниваем скорость list и np.array

In [127]:
%%timeit

[i * i for i in range(100000)]

7.91 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [126]:
%%timeit

a = np.arange(100000)
a * a

144 µs ± 4.61 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Pandas

 Позволяет работать с данными - читать, преобразовывать и сохранять

 ## Установка

 ```
 conda install pandas
 ```

In [139]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'